### ISSUE TITLE
No type declaration of "Function" and "Property Get" possible

### ISSUE THREAD

**Issue by juengling** [mkdocstrings/vba#17]
(Mkdocs v1.6.0, Python 3.12 on Windows 11)

You cannot specify a return type of a "Function" or a "Property Get". Anything before the ":" is reported as its "name". Unfortunately the type is not recognize from the property declaration (as it ist done for the "property let").

But in this case the command line complains with a warning: `WARNING -  griffe: <module>:9: No type or annotation for returned value 'String'`

**Example:**
```basic
Public Property Get Text() As String
' Retrieve Text property
'
' Returns:
'	String: Text property value
Text = MyString

End Property
```

**Result:**

![grafik](https://github.com/user-attachments/assets/0cb249da-63c4-4bc1-a585-8635eacc807a)

Trying the same example with a dummy name plus a type results in an endless loop, which terminates with `RecursionError: maximum recursion depth exceeded`.

```basic
' Returns:
'	Dummy (String): Text property value
```

See a minimum working example on [Gitlab](https://gitlab.com/juengling/mkdocs-tests/-/tree/Class-Properties).

**Comment by rudolfbyker** [comment]
Thanks for reporting. Please review #21
